<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.5.4</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>pe.gob.osinergmin.soa.sms</groupId>
	<artifactId>ws-sms</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>war</packaging>
	<name>ws-sms</name>
	<properties>
		<nexus.url>https://developer.osinerg.gob.pe/nexus/content/groups/public</nexus.url>
		<java.version>1.8</java.version>
		<cxf.version>2.7.12</cxf.version>
		<cxf.xjc.version>2.7.0</cxf.xjc.version>
		<apache.logging.version>1.1.3</apache.logging.version>
        <apache.io.version>1.3.2</apache.io.version>
        <slf4j.version>1.7.13</slf4j.version>
        <modelmapper.version>0.7.5</modelmapper.version>
		<apache.xml.resolver>1.2</apache.xml.resolver>
		<jackson.version>2.4.1.3</jackson.version>
        <spring.xml.version>3.1.1</spring.xml.version>
        
        <hibernate.jpa.version>1.0.0.Final</hibernate.jpa.version>
        <hibernate.annotation.version>3.4.0.GA</hibernate.annotation.version>
        <hibernate.em.version>3.4.0.GA</hibernate.em.version>
        <hibernate.core.version>3.3.2.GA</hibernate.core.version>
        <persistence.version>1.0</persistence.version>
        <jee.version>7.0</jee.version>
        <log4j.version>1.2.17</log4j.version>
        <jta.version>1.1</jta.version>
        <ojdbc.version>11.2.0.2.0</ojdbc.version>
        <java.source.version>1.6</java.source.version>
        <apache.collections.version>3.2.1</apache.collections.version>
        <dom4j.version>1.6.1</dom4j.version>
        <cglib.version>2.2</cglib.version>
        <ejb.version>3.1</ejb.version>
        <jaxws.version>2.1</jaxws.version>
        <jaxb.version>2.1</jaxb.version>
        <maven.dependency.plugin.version>2.8</maven.dependency.plugin.version>
        <maven.compiler.plugin.version>3.1.0</maven.compiler.plugin.version>
        <maven.surefire.plugin.version>2.17</maven.surefire.plugin.version>
        <cxf.plugin.version>2.7.12</cxf.plugin.version>
        <maven.ejb.plugin.version>2.3</maven.ejb.plugin.version>
        <maven.war.plugin.version>2.1.1</maven.war.plugin.version>
        <maven.ear.plugin.version>2.9</maven.ear.plugin.version>
        <weblogic.wls.version>10.3.5</weblogic.wls.version>
        <glassfish.embedded.version>3.0-Prelude-Embedded-m2</glassfish.embedded.version>
        <apache.lang.version>2.3</apache.lang.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <apache.xml.resolver>1.2</apache.xml.resolver>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>ch.qos.logback</groupId>
					<artifactId>logback-classic</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
	  		<groupId>org.springframework.boot</groupId>
	  		<artifactId>spring-boot-starter-tomcat</artifactId>
	 		 <scope>provided</scope>
		</dependency>
		
		<dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-frontend-jaxws</artifactId>
            <version>3.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
				<exclusion>
					<groupId>org.apache.geronimo.specs</groupId>
					<artifactId>geronimo-javamail_1.4_spec</artifactId>
				</exclusion>
				<exclusion>
					<groupId>asm</groupId>
					<artifactId>asm</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.sun.xml.bind</groupId>
					<artifactId>jaxb-impl</artifactId>
				</exclusion>
				<exclusion>
					<groupId>xml-resolver</groupId>
					<artifactId>xml-resolver</artifactId>
				</exclusion>
				 <exclusion>
					<groupId>org.apache.ws.commons.xmlschema</groupId>
					<artifactId>XmlSchema</artifactId>
				</exclusion>
            </exclusions>
        </dependency>
        <dependency>
			<groupId>org.apache.cxf</groupId>
			<artifactId>cxf-rt-frontend-jaxrs</artifactId>
    		<version>3.0.0</version>
			<exclusions>
				<exclusion>
					<groupId>aopalliance</groupId>
					<artifactId>aopalliance</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.sun.xml.bind</groupId>
					<artifactId>jaxb-impl</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.sun.xml.fastinfoset</groupId>
					<artifactId>FastInfoset</artifactId>
				</exclusion>
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
				<exclusion>
					<groupId>javax.xml.bind</groupId>
					<artifactId>jaxb-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.geronimo.specs</groupId>
					<artifactId>geronimo-activation_1.1_spec</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.geronimo.specs</groupId>
					<artifactId>geronimo-annotation_1.0_spec</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.geronimo.specs</groupId>
					<artifactId>geronimo-javamail_1.4_spec</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.geronimo.specs</groupId>
					<artifactId>geronimo-servlet_3.0_spec</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.geronimo.specs</groupId>
					<artifactId>geronimo-stax-api_1.0_spec</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.neethi</groupId>
					<artifactId>neethi</artifactId>
				</exclusion>
				 <exclusion>
					<groupId>org.apache.ws.commons.xmlschema</groupId>
					<artifactId>XmlSchema</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.codehaus.jettison</groupId>
					<artifactId>jettison</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.jetty</groupId>
					<artifactId>jetty-continuation</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.jetty</groupId>
					<artifactId>jetty-http</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.jetty</groupId>
					<artifactId>jetty-io</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.jetty</groupId>
					<artifactId>jetty-security</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.jetty</groupId>
					<artifactId>jetty-server</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.jetty</groupId>
					<artifactId>jetty-util</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>org.slf4j</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-aop</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-asm</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-beans</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-context</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-context-support</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-expression</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-web</artifactId>
				</exclusion>
				<exclusion>
					<groupId>wsdl4j</groupId>
					<artifactId>wsdl4j</artifactId>
				</exclusion>
				<exclusion>
                	<groupId>xerces</groupId>
					<artifactId>xercesImpl</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>xml-apis</groupId>
                    <artifactId>xml-apis</artifactId>
                </exclusion>
			</exclusions>
		</dependency>
		
		 <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-transports-http</artifactId>
            <version>3.0.0</version>
        </dependency>
        
        <!-- Nuevo -->
        
		 <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-databinding-aegis</artifactId>
            <version>3.0.0</version>
        </dependency>
        
		<dependency>
			<groupId>org.apache.abdera</groupId>
			<artifactId>abdera-core</artifactId>
			<version>1.1.3</version>
		</dependency>
		
		<dependency>
            <groupId>org.apache.xmlbeans</groupId>
            <artifactId>xmlbeans</artifactId>
            <version>2.6.0</version>
        </dependency>
        
        <!-- <dependency>
			<groupId>com.fasterxml.woodstox</groupId>
		 	<artifactId>woodstox-core</artifactId>
		 	<version>5.0.2</version>
		</dependency>
		
		<dependency>
		    <groupId>javax.xml.stream</groupId>
		    <artifactId>stax-api</artifactId>
		    <version>1.0</version>
		</dependency> -->
        
        <!-- Nuevo --> 
        
        <dependency>
            <groupId>org.apache.cxf.xjcplugins</groupId>
			<artifactId>cxf-xjc-ts</artifactId>
            <version>3.0.0</version>
            <exclusions>
				 <exclusion>
					<groupId>org.apache.ws.commons.xmlschema</groupId>
					<artifactId>XmlSchema</artifactId>
				</exclusion>
            </exclusions>
        </dependency>
        <!-- <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <version>${spring.version}</version>
        </dependency>--> 
        <dependency>
            <groupId>org.springframework.ws</groupId>
            <artifactId>spring-xml</artifactId>
            	<exclusions>
	            	<!-- <exclusion>
	            		<groupId>javax.xml.stream</groupId>
						<artifactId>stax-api</artifactId>
	            	</exclusion> -->
            	</exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-io</artifactId>
            <version>${apache.io.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-logging</groupId>
            <artifactId>commons-logging</artifactId>
            <version>${apache.logging.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.modelmapper</groupId>
            <artifactId>modelmapper</artifactId>
            <version>${modelmapper.version}</version>
        </dependency>
         <!-- <dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson.version}</version>
		</dependency> -->
        <dependency>
			<groupId>xml-resolver</groupId>
			<artifactId>xml-resolver</artifactId>
			<version>${apache.xml.resolver}</version>
		</dependency>

        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.10.0</version>  <!-- Usa la última versión disponible -->
        </dependency>
	</dependencies>

<profiles>
        <profile>
            <id>generacion</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.cxf</groupId>
                        <artifactId>cxf-codegen-plugin</artifactId>
                        <version>3.0.0</version>
                        <configuration>
                            <fork>once</fork>
                            <additionalJvmArgs>-Djava.endorsed.dirs=${endorsed.dir}</additionalJvmArgs>
                        </configuration>
                        <dependencies>
                            <dependency>
                                <groupId>com.sun.xml.bind</groupId>
                                <artifactId>jaxb-impl</artifactId>
                                <version>${jaxb.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>com.sun.xml.bind</groupId>
                                <artifactId>jaxb-xjc</artifactId>
                                <version>${jaxb.version}</version>
                            </dependency>
                        </dependencies>
                        <executions>
                            <execution>
                                <id>generate-sources</id>
                                <phase>generate-sources</phase>
                                <configuration>
                                    <sourceRoot>${basedir}/src/main/java</sourceRoot>
                                    <wsdlOptions>
                                        <wsdlOption>
                                            <wsdl>${basedir}/src/main/webapp/WEB-INF/wsdl/WsSms.wsdl</wsdl>
                                            <wsdlLocation>/WEB-INF/wsdl/WsSms.wsdl</wsdlLocation>
                                            <serviceName>WsSMSService</serviceName>
                                            <extraargs>
                                                <extraarg>-impl</extraarg>
                                                <extraarg>-verbose</extraarg>
                                                <extraarg>-databinding</extraarg>
                                                <extraarg>jaxb</extraarg>                                               
                                                <extraarg>-xjcargs,keep</extraarg>
                                            </extraargs>
                                            <bindingFiles>
                                                <bindingFile>${basedir}/src/main/resources/jxb_binding_common_ws.xml</bindingFile>
                                                <bindingFile>${basedir}/src/main/resources/jxb_binding_sms_ws.xml</bindingFile>
                                                <bindingFile>${basedir}/src/main/resources/jaxws_binding_sms.xml</bindingFile>
                                            </bindingFiles>
                                        </wsdlOption>
                                    </wsdlOptions>
                                </configuration>
                                <goals>
                                    <goal>wsdl2java</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>construccion</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>${maven.compiler.plugin.version}</version>
                        <configuration>
                            <source>${maven.compiler.source}</source>
                            <target>${maven.compiler.target}</target>
                            <compilerArguments>
                                <endorseddirs>${endorsed.dir}</endorseddirs>
                            </compilerArguments>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-dependency-plugin</artifactId>
                        <version>${maven.dependency.plugin.version}</version>
                        <executions>
                            <execution>
                                <phase>generate-sources</phase>
                                <goals>
                                    <goal>copy</goal>
                                </goals>
                                <configuration>
                                    <artifactItems>
                                        <artifactItem>
                                            <groupId>javax.xml.bind</groupId>
                                            <artifactId>jaxb-api</artifactId>
                                            <version>${jaxws.version}</version>
                                        </artifactItem>
                                        <artifactItem>
                                            <groupId>javax.xml.ws</groupId>
                                            <artifactId>jaxws-api</artifactId>
                                            <version>${jaxws.version}</version>
                                        </artifactItem>
                                        <artifactItem>
                                            <groupId>javax</groupId>
                                            <artifactId>javaee-endorsed-api</artifactId>
                                            <version>${jee.version}</version>
                                            <type>jar</type>
                                        </artifactItem>
                                    </artifactItems>
                                    <outputDirectory>${endorsed.dir}</outputDirectory>
                                    <silent>true</silent>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-war-plugin</artifactId>
                        <version>${maven.war.plugin.version}</version>
                        <configuration>
                            <failOnMissingWebXml>true</failOnMissingWebXml>
                            <ignoreWebxml>false</ignoreWebxml>
                            <webXml>src/main/webapp/WEB-INF/web.xml</webXml>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
			    <groupId>org.apache.maven.plugins</groupId>
			    <artifactId>maven-resources-plugin</artifactId>
			    <version>3.1.0</version>
			</plugin>  
		</plugins>
		
		<finalName>ws-sms</finalName>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/project.properties</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <excludes>
                    <exclude>**/project.properties</exclude>
                </excludes>
            </resource>
            <resource>
                <directory>${project.build.directory}/generated/cxf</directory>
            </resource>
        </resources>
	</build>

</project>
