
package pe.gob.osinergmin.soa.sms.ws.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2017-04-18T12:56:26.811-05:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "falla", targetNamespace = "http://soa.osinergmin.gob.pe/schema/comun/fault")
public class ComunFaultMsg extends Exception {
    
    private pe.gob.osinergmin.soa.sms.ws.schema.comun.fault.OsinergminFaultTYPE falla;

    public ComunFaultMsg() {
        super();
    }
    
    public ComunFaultMsg(String message) {
        super(message);
    }
    
    public ComunFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ComunFaultMsg(String message, pe.gob.osinergmin.soa.sms.ws.schema.comun.fault.OsinergminFaultTYPE falla) {
        super(message);
        this.falla = falla;
    }

    public ComunFaultMsg(String message, pe.gob.osinergmin.soa.sms.ws.schema.comun.fault.OsinergminFaultTYPE falla, Throwable cause) {
        super(message, cause);
        this.falla = falla;
    }

    public pe.gob.osinergmin.soa.sms.ws.schema.comun.fault.OsinergminFaultTYPE getFaultInfo() {
        return this.falla;
    }
}
