package pe.gob.osinergmin.soa.sms.ws.service;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2017-04-18T12:56:26.889-05:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "WsSMSService", 
                  wsdlLocation = "/WEB-INF/wsdl/WsSms.wsdl",
                  targetNamespace = "http://soa.osinergmin.gob.pe/schema/wssms") 
public class WsSMSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soa.osinergmin.gob.pe/schema/wssms", "WsSMSService");
    public final static QName WsSMSPortSOAP12 = new QName("http://soa.osinergmin.gob.pe/schema/wssms", "WsSMSPortSOAP12");
    public final static QName WsSMSPortSOAP11 = new QName("http://soa.osinergmin.gob.pe/schema/wssms", "WsSMSPortSOAP11");
    static {
        URL url = WsSMSService.class.getResource("/WEB-INF/wsdl/WsSms.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(WsSMSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/WEB-INF/wsdl/WsSms.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public WsSMSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsSMSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsSMSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsSMSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsSMSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsSMSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WsSMSPort
     */
    //@WebEndpoint(name = "WsSMSPortSOAP12")
    //public WsSMSPort getWsSMSPortSOAP12() {
    //    return super.getPort(WsSMSPortSOAP12, WsSMSPort.class);
    //}

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsSMSPort
     */
    //@WebEndpoint(name = "WsSMSPortSOAP12")
    //public WsSMSPort getWsSMSPortSOAP12(WebServiceFeature... features) {
    //    return super.getPort(WsSMSPortSOAP12, WsSMSPort.class, features);
    //}
    /**
     *
     * @return
     *     returns WsSMSPort
     */
    @WebEndpoint(name = "WsSMSPortSOAP11")
    public WsSMSPort getWsSMSPortSOAP11() {
        return super.getPort(WsSMSPortSOAP11, WsSMSPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsSMSPort
     */
    @WebEndpoint(name = "WsSMSPortSOAP11")
    public WsSMSPort getWsSMSPortSOAP11(WebServiceFeature... features) {
        return super.getPort(WsSMSPortSOAP11, WsSMSPort.class, features);
    }

}
