package pe.gob.osinergmin.soa.sms.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2017-04-18T12:56:26.883-05:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://soa.osinergmin.gob.pe/schema/wssms", name = "WsSMSPort")
@XmlSeeAlso({pe.gob.osinergmin.soa.sms.ws.schema.ObjectFactory.class, pe.gob.osinergmin.soa.sms.ws.schema.comun.fault.ObjectFactory.class, pe.gob.osinergmin.soa.sms.ws.schema.comun.consumidor.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WsSMSPort {

    @WebResult(name = "recibeSMSRespParamTYPE", targetNamespace = "http://soa.osinergmin.gob.pe/schema/wssms", partName = "out")
    @WebMethod(action = "http://soa.osinergmin.gob.pe/schema/wssms/recibeSMS")
    public pe.gob.osinergmin.soa.sms.ws.schema.RecibeSMSRespParamTYPE recibeSMS(
        @WebParam(partName = "in", name = "recibeSMSReqParamTYPE", targetNamespace = "http://soa.osinergmin.gob.pe/schema/wssms")
        pe.gob.osinergmin.soa.sms.ws.schema.RecibeSMSReqParamTYPE in,
        @WebParam(partName = "consumidor", name = "consumidor", targetNamespace = "http://soa.osinergmin.gob.pe/schema/comun/consumidor", header = true)
        pe.gob.osinergmin.soa.sms.ws.schema.comun.consumidor.ConsumidorTYPE consumidor
    ) throws ComunFaultMsg;

    @WebResult(name = "enviarSMSRespParamTYPE", targetNamespace = "http://soa.osinergmin.gob.pe/schema/wssms", partName = "out")
    @WebMethod(action = "http://soa.osinergmin.gob.pe/schema/wssms/enviarSMS")
    public pe.gob.osinergmin.soa.sms.ws.schema.EnviarSMSRespParamTYPE enviarSMS(
        @WebParam(partName = "in", name = "enviarSMSReqParamTYPE", targetNamespace = "http://soa.osinergmin.gob.pe/schema/wssms")
        pe.gob.osinergmin.soa.sms.ws.schema.EnviarSMSReqParamTYPE in,
        @WebParam(partName = "consumidor", name = "consumidor", targetNamespace = "http://soa.osinergmin.gob.pe/schema/comun/consumidor", header = true)
        pe.gob.osinergmin.soa.sms.ws.schema.comun.consumidor.ConsumidorTYPE consumidor
    ) throws ComunFaultMsg;
    
    @WebResult(name = "voiceSMSRespParamTYPE", targetNamespace = "http://soa.osinergmin.gob.pe/schema/wssms", partName = "out")
    @WebMethod(operationName = "voiceSMS", action = "http://soa.osinergmin.gob.pe/schema/wssms/voiceSMS")
    public pe.gob.osinergmin.soa.sms.ws.schema.EnviarVoiceRespParamTYPE voiceSMS(
        @WebParam(partName = "in", name = "voiceSMSReqParamTYPE", targetNamespace = "http://soa.osinergmin.gob.pe/schema/wssms")
        pe.gob.osinergmin.soa.sms.ws.schema.EnviarVoiceReqParamTYPE in,
        @WebParam(partName = "consumidor", name = "consumidor", targetNamespace = "http://soa.osinergmin.gob.pe/schema/comun/consumidor", header = true)
        pe.gob.osinergmin.soa.sms.ws.schema.comun.consumidor.ConsumidorTYPE consumidor
    ) throws ComunFaultMsg;

    
}
