prefijo_TK=TK
prefijo_SGP=SGP
prefijo_PRC=PRC
prefijo_SCOP=SCOP

sms_ws_provider=I

tedexis_wsdl_url=http://200.41.57.109:8086/m4.in.wsint/services/M4WSIntSR?wsdl
tedexis_passport=TDXOSIOP1
tedexis_password=GLuPvZX3

infobip_ws_url=https://api.infobip.com/sms/1/text/single
infobip_ws_user=Osinergmincentral
infobip_ws_password=Osinergmin2019

scop_ordenservicio_wsdl_url_desa=https://scopwsdesa.osinergmin.gob.pe/scopws/services/OrdenPedidoService?wsdl
scop_ordenservicio_wsdl_url=https://scopws.osinergmin.gob.pe/scopws/services/OrdenPedidoService?wsdl

sargop_wsdl_url=http://11.160.124.103:7005/ws-sargop/services/Sargop?wsdl

precios_wsdl_url=http://localhost:7001/precios-ws/services/Precios?wsdl

sargop_recibe_sms_url=http://11.160.124.103:7005/ws-sargop/services/Sargop11
